name: ct_festival
description: "Web Application for Cape Town Festival 2025, enabling visitor registration, event RSVPs, and feedback collection using Flutter and Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  #carousel
  carousel_slider: ^5.0.0

  #weather
  weather: ^3.1.1
  font_awesome_flutter: ^10.8.0

  #image cloud storage
  cloudinary_public: ^0.23.1
  file_picker: ^9.0.2
  path: ^1.9.1

  #google maps
  google_maps_flutter: ^2.10.1
  web: ^1.1.1

  #data visualisation
  pie_chart: ^5.4.0
  fl_chart: ^0.70.2

  #time
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  #cloud storage
  cloudinary_sdk: ^5.0.0+1

  #state management
  flutter_riverpod: ^2.6.1

  #email verification
  http: ^1.3.0

  #firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4


  #logger
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/ct_logo.png
