name: ct_festival
description: "Web Application for Cape Town Festival 2025, enabling visitor registration, event RSVPs, and feedback collection using Flutter and Firebase."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8

  #cloud storage
  cloudinary_sdk: ^5.0.0+1

  #state management
  flutter_riverpod: ^2.6.1

  #email verification
  http: ^1.3.0

  #firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2

  #logger
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/ct_logo.png
