name: ct_festival
description: "Web Application for Cape Town Festival 2025, enabling visitor registration, event RSVPs, and feedback collection using Flutter and Firebase."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8

  #firebase
  firebase_core: ^3.11.0

  #logger
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/ct_logo.png
